name: Android CI - Build APK (self-contained SDK install)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
- name: Install prerequisites

  env:
    ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
  run: |
    mkdir -p "$ANDROID_SDK_ROOT"
    # ... rest of commands

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin

    - name: Install prerequisites
      run: |
        sudo apt-get update -y
        sudo apt-get install -y unzip wget zip

    - name: Download Android command-line tools
      run: |
        mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
        cd "${ANDROID_SDK_ROOT}"
        TOOL_ZIP="commandlinetools-linux-11076708_latest.zip"
        URL="https://dl.google.com/android/repository/${TOOL_ZIP}"
        wget -q --show-progress -O cmdline-tools.zip "$URL" || (echo "cmdline-tools download failed" && exit 2)
        unzip -q -o cmdline-tools.zip -d cmdline-tools
        mkdir -p cmdline-tools/latest
        if [ -d cmdline-tools/cmdline-tools ]; then
          mv -f cmdline-tools/cmdline-tools/* cmdline-tools/latest/ || true
        else
          mv -f cmdline-tools/* cmdline-tools/latest/ || true
        fi
        rm -f cmdline-tools.zip

    - name: Add sdkmanager to PATH and accept licenses
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        PATH: ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:${PATH}
      run: |
        yes | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses || true

    - name: Install platform-tools, platform and build-tools
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        PATH: ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:${PATH}
      run: |
        sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Show installed SDK contents
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
      run: |
        ls -la "${ANDROID_SDK_ROOT}"
        ls -la "${ANDROID_SDK_ROOT}/build-tools" || true
        "${ANDROID_SDK_ROOT}/build-tools/34.0.0/aapt2" --version 2>/dev/null || echo "aapt2 check skipped or not executable"

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build (assembleDebug)
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        PATH: ${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:${PATH}
      run: ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: |
          **/app/build/outputs/apk/debug/*.apk
